run:
  tests: true
  build-tags:
    - bench
    - !bench

linters-settings:
  funlen:
    lines: 150
    statements: 80
  depguard:
    rules:
      Main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - golang.org/x/example/hello
          - github.com/HelenaBlack/hw_otus/hw12_13_14_15_calendar/internal/app
          - github.com/HelenaBlack/hw_otus/hw12_13_14_15_calendar/internal/logger
          - github.com/HelenaBlack/hw_otus/hw12_13_14_15_calendar/internal/configs
          - github.com/HelenaBlack/hw_otus/hw12_13_14_15_calendar/internal/storage
          - github.com/HelenaBlack/hw_otus/hw12_13_14_15_calendar/internal/server/http
          - github.com/HelenaBlack/hw_otus/hw12_13_14_15_calendar/internal/storage/memory
          - github.com/HelenaBlack/hw_otus/hw12_13_14_15_calendar/internal/storage/sql
          - github.com/google/uuid
          - github.com/pressly/goose/v3
          - gopkg.in/yaml.v2
          - github.com/jmoiron/sqlx
      Test:
        files:
          - $test
        allow:
          - $gostd
          - github.com/stretchr/testify
          - golang.org/x/example/hello
          - github.com/pressly/goose/v3
          - github.com/lib/pq
          - github.com/HelenaBlack/hw_otus/hw12_13_14_15_calendar/internal/app
          - github.com/HelenaBlack/hw_otus/hw12_13_14_15_calendar/internal/storage


issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec

linters:
  disable-all: true
  enable:
    - asciicheck
    - depguard
    - dogsled
    - dupl
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
